[RM][Usability] - Permissions on Reference Manager
ResearchHub/researchhub-backend pull request #1279
Opened 2023-05-15 19:24 UTC by calvinhlee23

2023-05-16 19:58 UTC, calvinhlee23 commented on src/citation/views/citation_project_view.py
> +    def create(self, _request):
yes. Otherwise, it uses default serializer methods.

2023-05-16 23:23 UTC, le-sun requested changes

2023-05-16 23:23 UTC, le-sun commented on src/citation/views/citation_project_view.py
> +        # with transaction.atomic:
Let's bring back the atomicity.

2023-05-16 23:23 UTC, le-sun commented on src/citation/related_models/citation_project.py
> +            return False
What's the point of capturing the errors? We should log these too with sentry.

2023-05-16 23:23 UTC, le-sun commented on src/citation/serializers/citation_project_serializer.py
>              pass
Why the try/catch? Also, return false?

2023-05-16 23:23 UTC, le-sun commented on src/citation/related_models/citation_project.py
> +            return False
Same as above

2023-05-16 23:23 UTC, le-sun commented on src/citation/views/citation_entry_view.py
> +                citations_query = citations_query.filter(created_by=user.id)
We should do filtering with a `filter_class` instead. See `researchhub_comment/filters.py` for a recent example.

2023-05-16 23:23 UTC, le-sun commented on src/citation/views/citation_entry_view.py
> +            raise PermissionError("Fetch not allowed without org_id or project_id")
If we add a `filter_class`, we can set the field to be required and we won't need to manually raise this exception.

2023-05-19 20:56 UTC, le-sun approved these changes

2023-05-19 20:56 UTC, merged