[RefManager] - DOI / URL Upload
ResearchHub/researchhub-backend pull request #1314
Opened 2023-07-07 20:55 UTC by calvinhlee23

2023-07-07 21:26 UTC, le-sun requested changes
Small change

2023-07-07 21:26 UTC, le-sun commented on src/citation/views/citation_entry_view.py
> +            scraper_result = cloudscraper.create_scraper().get(url_string)
Let's put a timeout inside `.get(...)`

2023-07-10 15:23 UTC, yattias commented on src/citation/views/citation_entry_view.py
> +                    r"10.\d{4,9}\/[-._;()\/:a-zA-Z0-9]+?(?=[\";%<>\?#&])", str(content)
I've seen DOI regex used in a bunch of locations. Can we store it externally somewhere in a constant?

2023-07-10 23:24 UTC, le-sun approved these changes

2023-07-10 23:25 UTC, le-sun requested changes

2023-07-10 23:25 UTC, le-sun commented on src/citation/views/citation_entry_view.py
> +                open_alex_result = open_alex.get_data_from_doi(formmated_dois[0])
It's possible to have an empty list, so we need to put a check in for that.

2023-07-13 22:17 UTC, merged