Automated biorxiv bounties
ResearchHub/researchhub-backend pull request #1371
Opened 2023-10-09 17:45 UTC by lightninglu10

Automate biorxiv bounties if they get above 10 upvotes

2023-10-09 22:18 UTC, le-sun requested changes

2023-10-09 22:18 UTC, le-sun commented on src/discussion/reaction_views.py
> +        capture_exception(e)
Let's use `from utils.sentry import log_error` here

2023-10-09 22:18 UTC, le-sun commented on src/researchhub/settings.py
> +AWS_S3_CUSTOM_DOMAIN = "d2ogkcqdn9wsvr.cloudfront.net"
Won't this break staging/dev?

2023-10-11 19:35 UTC, lightninglu10 commented on src/researchhub/settings.py
> +AWS_S3_CUSTOM_DOMAIN = "d2ogkcqdn9wsvr.cloudfront.net"
yep, need to update

2023-10-11 19:37 UTC, merged